runtime: nodejs
env: flex
env_variables:
  SQL_USER: YOUR_SQL_USER
  SQL_PASSWORD: YOUR_SQL_PASSWORD
  SQL_DATABASE: YOUR_SQL_DATABASE
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: YOUR_INSTANCE_CONNECTION_NAME